name: Veracode Static Analysis Pipeline Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '23 12 * * 3'

permissions:
  contents: read

jobs:
  build-and-pipeline-scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
    - name: Checkout only necessary folders (sparse)
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        sparse-checkout: |
          force-app/main/default/classes
          force-app/main/default/lwsc
        sparse-checkout-cone-mode: false

    - name: Filter and zip only .cls and .js files
      run: |
        mkdir -p filtered
        find force-app/main/default/classes -type f -name "*.cls" -exec cp --parents {} filtered/ \;
        find force-app/main/default/lwsc -type f -name "*.js" -exec cp --parents {} filtered/ \;
        zip -r veracode-scan-target.zip filtered

    - name: Download Veracode Pipeline Scan
      run: |
        curl --silent --show-error --fail -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
        unzip -o pipeline-scan-LATEST.zip

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: 'temurin'

    - name: Run Veracode Pipeline Scan
      run: java -jar pipeline-scan.jar --veracode_api_id "${{ secrets.VERACODE_API_ID }}" --veracode_api_key "${{ secrets.VERACODE_API_KEY }}" --fail_on_severity="Very High, High" --file veracode-scan-target.zip
      continue-on-error: true

    - name: Convert pipeline scan output to SARIF format
      id: convert
      uses: veracode/veracode-pipeline-scan-results-to-sarif@ff08ae5b45d5384cb4679932f184c013d34da9be
      with:
        pipeline-results-json: results.json

    - name: Upload SARIF to GitHub code scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: veracode-results.sarif
